pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Shubh039/CapstoneProject_testNG'
            }
        }

        stage('Build') {
            steps {
                dir('ParabankAutomation') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Run Negative Tests') {
            steps {
                dir('ParabankAutomation') {
                    bat 'mvn test -Dsurefire.suiteXmlFiles=testng-negative.xml'
                }
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'ParabankAutomation/reports/**/*',
                                 allowEmptyArchive: true

                archiveArtifacts artifacts: 'ParabankAutomation/screenshots/**/*',
                                 allowEmptyArchive: true

                archiveArtifacts artifacts: 'ParabankAutomation/logs/**/*',
                                 allowEmptyArchive: true
            }
        }
    }

    post {

        always {
            junit allowEmptyResults: true,
                  testResults: 'ParabankAutomation/**/target/surefire-reports/*.xml'
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}